# Generated by Django 2.1.4 on 2018-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='air_date',
            field=models.DateField(),
        ),
    ]
